spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db/shopping?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root123

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
