version: "3.8"
services:
  db:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: shopping
    volumes:
      - ../src/main/resources/db:/docker-entrypoint-initdb.d
    restart: always
